openapi: 3.0.1
info:
  contact:
    name: Skash
    url: https://github.com/0xSkash
  description: API Docs for the Time Track Backend
  title: Time Track API Docs
  version: 1.0.0
servers:
- url: /
tags:
- description: Fetching and creating of clients per workspace
  name: Client
paths:
  /organizations/{organizationId}/workspaces/{workspaceId}/clients:
    get:
      deprecated: false
      description: Endpoint for Client fetching
      parameters:
      - deprecated: false
        description: Bearer Token used to authenticate user
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - deprecated: false
        explode: false
        in: path
        name: organizationId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - deprecated: false
        explode: false
        in: path
        name: workspaceId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "401":
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ClientResponse'
                type: array
          description: List of Clients of the specified workspace
        "400":
          description: Workspace does not exist
      summary: Returns all Clients who belong to the specified workspace
      tags:
      - Client
      x-accepts: application/json
    post:
      deprecated: false
      description: Endpoint for Client Creation
      parameters:
      - deprecated: false
        description: Bearer Token used to authenticate user
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - deprecated: false
        explode: false
        in: path
        name: organizationId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - deprecated: false
        explode: false
        in: path
        name: workspaceId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "401":
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
          description: The created client
        "400":
          description: Workspace does not exist
      summary: Creates a client for the specified workspace
      tags:
      - Client
      x-accepts: application/json
components:
  schemas:
    ClientResponse:
      example:
        title: Example Title
        isBillable: true
      properties:
        title:
          example: Example Title
          type: string
        isBillable:
          example: true
          type: boolean
      type: object
  securitySchemes: {}

